"""apimaticapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.configurations.endpoint_configuration import (
    EndpointConfiguration,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from apimaticapi.api_helper import APIHelper
from apimaticapi.configuration import Server
from apimaticapi.controllers.base_controller import (
    BaseController,
)
from apimaticapi.exceptions.api_exception import (
    ApiException,
)
from apimaticapi.exceptions.internal_server_error_response_exception import (
    InternalServerErrorResponseException,
)
from apimaticapi.exceptions.problem_details_exception import (
    ProblemDetailsException,
)
from apimaticapi.exceptions.unauthorized_response_exception import (
    UnauthorizedResponseException,
)
from apimaticapi.http.http_method_enum import (
    HttpMethodEnum,
)


class DocsPortalManagementController(BaseController):
    """A Controller to access Endpoints in the apimaticapi API."""

    def __init__(self, config):
        """Initialize DocsPortalManagementController object."""
        super(DocsPortalManagementController, self).__init__(config)

    def generate_on_prem_portal_via_build_input(self,
                                                content_type,
                                                file,
                                                _optional_query_parameters=None):
        """Perform a POST request to /portal.

        Generate an On-premise Documentation Portal by uploading a Portal Build
        Input. This endpoint generates all artifacts for the Portal and packages them
        together into a zip file along with the required HTML, CSS and JS files. The
        generated artifacts include:
        1. SDKs
        2. Docs
        3. API Specification files
        The endpoint returns a zip file that contains a static Site and can be hosted
        on any Web Server.

        Args:
            content_type (ContentType): The request header parameter.
            file (typing.BinaryIO): The input file to the Portal Generator. Must
                contain the build file.
            _optional_query_parameters (Array, optional): Additional optional query
                parameters are supported by this endpoint

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers.

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/portal")
            .http_method(HttpMethodEnum.POST)
            .multipart_param(Parameter()
                .key("file")
                .value(file)
                .default_content_type("application/octet-stream")
                .is_required(True))
            .additional_query_params(_optional_query_parameters)
            .auth(Single("Authorization")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .is_api_response(True)
            .local_error("400", "Bad Request", ProblemDetailsException)
            .local_error("401", "Unauthorized", UnauthorizedResponseException)
            .local_error("403", "Subscription Issue", ProblemDetailsException)
            .local_error("422",
                "Unprocessable Entity - Contains error.zip for build issues",
                ApiException)
            .local_error("500",
                "Internal Server Error",
                InternalServerErrorResponseException),
        ).endpoint_configuration(
            EndpointConfiguration()
            .has_binary_response(True),
        ).execute()
