"""apimaticapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimatic_core.configurations.global_configuration import (
    GlobalConfiguration,
)
from apimatic_core.decorators.lazy_property import (
    LazyProperty,
)

from apimaticapi.configuration import (
    Configuration,
    Environment,
)
from apimaticapi.controllers.api_validation_external_apis_controller import (
    ApiValidationExternalApisController,
)
from apimaticapi.controllers.api_validation_v_2_external_apis_controller import (
    ApiValidationV2ExternalApisController,
)
from apimaticapi.controllers.base_controller import (
    BaseController,
)
from apimaticapi.controllers.code_generation_external_apis_controller import (
    CodeGenerationExternalApisController,
)
from apimaticapi.controllers.docs_portal_generation_async_controller import (
    DocsPortalGenerationAsyncController,
)
from apimaticapi.controllers.docs_portal_management_controller import (
    DocsPortalManagementController,
)
from apimaticapi.controllers.sdk_generation_async_controller import (
    SdkGenerationAsyncController,
)
from apimaticapi.controllers.transformation_controller import (
    TransformationController,
)
from apimaticapi.http.auth.custom_header_authentication import (
    CustomHeaderAuthentication,
)


class ApimaticapiClient(object):
    """Client that provide access to the ApimaticapiClient APIs."""

    @LazyProperty
    def code_generation_external_apis(self):
        """Provide access to the CodeGenerationExternalApisController endpoints."""
        return CodeGenerationExternalApisController(self.global_configuration)

    @LazyProperty
    def transformation(self):
        """Provide access to the TransformationController endpoints."""
        return TransformationController(self.global_configuration)

    @LazyProperty
    def docs_portal_management(self):
        """Provide access to the DocsPortalManagementController endpoints."""
        return DocsPortalManagementController(self.global_configuration)

    @LazyProperty
    def docs_portal_generation_async(self):
        """Provide access to the DocsPortalGenerationAsyncController endpoints."""
        return DocsPortalGenerationAsyncController(self.global_configuration)

    @LazyProperty
    def api_validation_external_apis(self):
        """Provide access to the ApiValidationExternalApisController endpoints."""
        return ApiValidationExternalApisController(self.global_configuration)

    @LazyProperty
    def api_validation_v_2_external_apis(self):
        """Provide access to the ApiValidationV2ExternalApisController endpoints."""
        return ApiValidationV2ExternalApisController(self.global_configuration)

    @LazyProperty
    def sdk_generation_async(self):
        """Provide access to the SdkGenerationAsyncController endpoints."""
        return SdkGenerationAsyncController(self.global_configuration)

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, http_call_back=None,
                 timeout=30, max_retries=0, backoff_factor=2,
                 retry_statuses=None, retry_methods=None, proxy_settings=None,
                 logging_configuration=None, environment=Environment.PRODUCTION,
                 custom_url="https://localhost:44301/api",
                 custom_header_authentication_credentials=None,
                 user_agent="TODO: Replace", config=None):
        """Initialize a new instance of ApimaticapiClient."""
        self.config = config or Configuration(
            http_client_instance=http_client_instance,
            override_http_client_configuration=override_http_client_configuration,
            http_call_back=http_call_back, timeout=timeout,
            max_retries=max_retries, backoff_factor=backoff_factor,
            retry_statuses=retry_statuses, retry_methods=retry_methods,
            proxy_settings=proxy_settings,
            logging_configuration=logging_configuration,
            environment=environment, custom_url=custom_url,
            custom_header_authentication_credentials=custom_header_authentication_credentials,
            user_agent=user_agent)

        self.global_configuration = GlobalConfiguration(self.config)\
            .global_errors(BaseController.global_errors())\
            .base_uri_executor(self.config.get_base_uri)\
            .global_header("user-agent",
                self.config.user_agent)

        self.auth_managers = {
            "Authorization": CustomHeaderAuthentication(
                self.config.custom_header_authentication_credentials),
        }
        self.global_configuration =\
            self.global_configuration.auth_managers(self.auth_managers)

    @classmethod
    def from_environment(cls, dotenv_path=None, **overrides):
        """Create a client instance using environment variables.

        Returns:
            ApimaticapiClient instance.

        """
        return cls(config=Configuration
            .from_environment(dotenv_path=dotenv_path, **overrides))
