# -*- coding: utf-8 -*-

"""
apimaticapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from apimaticapi.api_helper import APIHelper


class APIValidationExternalApisControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(APIValidationExternalApisControllerTests, cls).setUpClass()
        cls.controller = cls.client.api_validation_external_apis
        cls.response_catcher = cls.controller.http_call_back

    # Validate an API by providing the URL of the API specification file.
    #
    #You can also specify [API Metadata](https://docs.apimatic.io/manage-apis/apimatic-metadata) while validating the API using this endpoint. When specifying Metadata, the URL provided will be that of a zip file containing the API specification file and the `APIMATIC-META` json file.
    def test_validate_api_via_url(self):
        # Parameters for the API call
        description_url = 'https://petstore.swagger.io/v2/swagger.json'

        # Perform the API call through the SDK function
        result = self.controller.validate_api_via_url(description_url)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"success":true,"errors":[],"warnings":["Media type <i><code>appli'
            'cation/json; charset=utf-8</code></i> content definition of respon'
            'se code <i><code>429</code></i> in endpoint <i><code>getRealTimeDa'
            'ta</code></i> of group <i><code>data</code></i> contains an exampl'
            'e value with following undeclared fields: <i><code>detail</i></cod'
            'e>.","Endpoint <i><code>getRealTimeData</code></i> has an example '
            'specified for error code <i><code>429</code></i> which contains fo'
            'llowing undeclared fields: <i><code>detail</i></code>.","Media typ'
            'e <i><code>application/json; charset=utf-8</code></i> content defi'
            'nition of response code <i><code>429</code></i> in endpoint <i><co'
            'de>getDataPerCategory</code></i> of group <i><code>data</code></i>'
            ' contains an example value with following undeclared fields: <i><c'
            'ode>detail</i></code>.","Endpoint <i><code>getDataPerCategory</cod'
            'e></i> has an example specified for error code <i><code>429</code>'
            '</i> which contains following undeclared fields: <i><code>detail</'
            'i></code>.","Media type <i><code>application/json; charset=utf-8</'
            'code></i> content definition of response code <i><code>429</code><'
            '/i> in endpoint <i><code>getData</code></i> of group <i><code>data'
            '</code></i> contains an example value with following undeclared fi'
            'elds: <i><code>detail</i></code>.","Endpoint <i><code>getData</cod'
            'e></i> has an example specified for error code <i><code>429</code>'
            '</i> which contains following undeclared fields: <i><code>detail</'
            'i></code>.","Media type <i><code>application/json; charset=utf-8</'
            'code></i> content definition of response code <i><code>429</code><'
            '/i> in endpoint <i><code>getActiveStatuses</code></i> of group <i>'
            '<code>statuses</code></i> contains an example value with following'
            ' undeclared fields: <i><code>detail</i></code>.","Endpoint <i><cod'
            'e>getActiveStatuses</code></i> has an example specified for error '
            'code <i><code>429</code></i> which contains following undeclared f'
            'ields: <i><code>detail</i></code>.","Media type <i><code>applicati'
            'on/json; charset=utf-8</code></i> content definition of response c'
            'ode <i><code>200</code></i> in endpoint <i><code>getDevices</code>'
            '</i> of group <i><code>assets</code></i> contains an example value'
            ' with following undeclared fields: <i><code>deviceModelId</code></'
            'i>, <i><code>manufacturer</code></i>, <i><code>model</i></code>.",'
            '"Media type <i><code>application/json; charset=utf-8</code></i> co'
            'ntent definition of response code <i><code>429</code></i> in endpo'
            'int <i><code>getDevices</code></i> of group <i><code>assets</code>'
            '</i> contains an example value with following undeclared fields: <'
            'i><code>detail</i></code>.","Endpoint <i><code>getDevices</code></'
            'i> has an example specified for error code <i><code>429</code></i>'
            ' which contains following undeclared fields: <i><code>detail</i></'
            'code>.","Media type <i><code>application/json; charset=utf-8</code'
            '></i> content definition of response code <i><code>429</code></i> '
            'in endpoint <i><code>getAlarms</code></i> of group <i><code>alerts'
            '</code></i> contains an example value with following undeclared fi'
            'elds: <i><code>detail</i></code>.","Endpoint <i><code>getAlarms</c'
            'ode></i> has an example specified for error code <i><code>429</cod'
            'e></i> which contains following undeclared fields: <i><code>detail'
            '</i></code>.","Media type <i><code>application/json; charset=utf-8'
            '</code></i> content definition of response code <i><code>429</code'
            '></i> in endpoint <i><code>getActiveAlerts</code></i> of group <i>'
            '<code>alerts</code></i> contains an example value with following u'
            'ndeclared fields: <i><code>detail</i></code>.","Endpoint <i><code>'
            'getActiveAlerts</code></i> has an example specified for error code'
            ' <i><code>429</code></i> which contains following undeclared field'
            's: <i><code>detail</i></code>.","Media type <i><code>application/j'
            'son; charset=utf-8</code></i> content definition of response code '
            '<i><code>429</code></i> in endpoint <i><code>getAlerts</code></i> '
            'of group <i><code>alerts</code></i> contains an example value with'
            ' following undeclared fields: <i><code>detail</i></code>.","Endpoi'
            'nt <i><code>getAlerts</code></i> has an example specified for erro'
            'r code <i><code>429</code></i> which contains following undeclared'
            ' fields: <i><code>detail</i></code>.","Media type <i><code>applica'
            'tion/json; charset=utf-8</code></i> content definition of response'
            ' code <i><code>429</code></i> in endpoint <i><code>getConfiguratio'
            'n</code></i> of group <i><code>configuration data</code></i> conta'
            'ins an example value with following undeclared fields: <i><code>de'
            'tail</i></code>.","Endpoint <i><code>getConfiguration</code></i> h'
            'as an example specified for error code <i><code>429</code></i> whi'
            'ch contains following undeclared fields: <i><code>detail</i></code'
            '>.","Media type <i><code>application/json; charset=utf-8</code></i'
            '> content definition of response code <i><code>429</code></i> in e'
            'ndpoint <i><code>getActiveAlarms</code></i> of group <i><code>aler'
            'ts</code></i> contains an example value with following undeclared '
            'fields: <i><code>detail</i></code>.","Endpoint <i><code>getActiveA'
            'larms</code></i> has an example specified for error code <i><code>'
            '429</code></i> which contains following undeclared fields: <i><cod'
            'e>detail</i></code>.","Media type <i><code>application/json; chars'
            'et=utf-8</code></i> content definition of response code <i><code>4'
            '29</code></i> in endpoint <i><code>getPowerCurves</code></i> of gr'
            'oup <i><code>assets</code></i> contains an example value with foll'
            'owing undeclared fields: <i><code>detail</i></code>.","Endpoint <i'
            '><code>getPowerCurves</code></i> has an example specified for erro'
            'r code <i><code>429</code></i> which contains following undeclared'
            ' fields: <i><code>detail</i></code>.","Media type <i><code>applica'
            'tion/json; charset=utf-8</code></i> content definition of response'
            ' code <i><code>429</code></i> in endpoint <i><code>getDataSignals<'
            '/code></i> of group <i><code>data</code></i> contains an example v'
            'alue with following undeclared fields: <i><code>detail</i></code>.'
            '","Endpoint <i><code>getDataSignals</code></i> has an example spec'
            'ified for error code <i><code>429</code></i> which contains follow'
            'ing undeclared fields: <i><code>detail</i></code>.","Media type <i'
            '><code>application/json; charset=utf-8</code></i> content definiti'
            'on of response code <i><code>429</code></i> in endpoint <i><code>g'
            'etStatuses</code></i> of group <i><code>statuses</code></i> contai'
            'ns an example value with following undeclared fields: <i><code>det'
            'ail</i></code>.","Endpoint <i><code>getStatuses</code></i> has an '
            'example specified for error code <i><code>429</code></i> which con'
            'tains following undeclared fields: <i><code>detail</i></code>.","M'
            'edia type <i><code>application/json; charset=utf-8</code></i> cont'
            'ent definition of response code <i><code>429</code></i> in endpoin'
            't <i><code>getSites</code></i> of group <i><code>assets</code></i>'
            ' contains an example value with following undeclared fields: <i><c'
            'ode>detail</i></code>.","Endpoint <i><code>getSites</code></i> has'
            ' an example specified for error code <i><code>429</code></i> which'
            ' contains following undeclared fields: <i><code>detail</i></code>.'
            '"],"messages":["One or more elements in the API specification has '
            'a missing description field."]}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

