# -*- coding: utf-8 -*-

"""
apimaticapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from apimaticapi.api_helper import APIHelper


class TransformationControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(TransformationControllerTests, cls).setUpClass()
        cls.controller = cls.client.transformation
        cls.response_catcher = cls.controller.http_call_back

    # Get a list of all API transformations performed.
    def test_list_all_transformations(self):

        # Perform the API call through the SDK function
        result = self.controller.list_all_transformations()

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


