# -*- coding: utf-8 -*-

"""
apimaticapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class APIEntityIdentifier(object):

    """Implementation of the 'APIEntityIdentifier' model.

    TODO: type model description here.

    Attributes:
        api_entity_id (str): Unique API Entity Identifier

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "api_entity_id": 'apiEntityId'
    }

    def __init__(self,
                 api_entity_id=None):
        """Constructor for the APIEntityIdentifier class"""

        # Initialize members of the class
        self.api_entity_id = api_entity_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        api_entity_id = dictionary.get("apiEntityId") if dictionary.get("apiEntityId") else None
        # Return an object of this model
        return cls(api_entity_id)
