"""apimaticapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimaticapi.api_helper import APIHelper


class ApiValidationSummary(object):
    """Implementation of the 'ApiValidationSummary' model.

    Attributes:
        success (bool): The model property of type bool.
        errors (List[str]): The model property of type List[str].
        warnings (List[str]): The model property of type List[str].
        messages (List[str]): The model property of type List[str].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "success": "success",
        "errors": "errors",
        "warnings": "warnings",
        "messages": "messages",
    }

    def __init__(
        self,
        success=None,
        errors=None,
        warnings=None,
        messages=None,
        additional_properties=None):
        """Initialize a ApiValidationSummary instance."""
        # Initialize members of the class
        self.success = success
        self.errors = errors
        self.warnings = warnings
        self.messages = messages

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        success =\
            dictionary.get("success")\
            if "success" in dictionary.keys()\
                else None
        errors =\
            dictionary.get("errors")\
            if dictionary.get("errors")\
                else None
        warnings =\
            dictionary.get("warnings")\
            if dictionary.get("warnings")\
                else None
        messages =\
            dictionary.get("messages")\
            if dictionary.get("messages")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(success,
                   errors,
                   warnings,
                   messages,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _success=self.success
        _errors=self.errors
        _warnings=self.warnings
        _messages=self.messages
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"success={_success!r}, "
            f"errors={_errors!r}, "
            f"warnings={_warnings!r}, "
            f"messages={_messages!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _success=self.success
        _errors=self.errors
        _warnings=self.warnings
        _messages=self.messages
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"success={_success!s}, "
            f"errors={_errors!s}, "
            f"warnings={_warnings!s}, "
            f"messages={_messages!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
