# -*- coding: utf-8 -*-

"""
apimaticapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class EndpointsGroup(object):

    """Implementation of the 'EndpointsGroup' model.

    This structure encapsulates all the attributes of an API Endpoints Group.

    Attributes:
        name (str): TODO: type description here.
        description (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": 'name',
        "description": 'description'
    }

    def __init__(self,
                 name=None,
                 description=None):
        """Constructor for the EndpointsGroup class"""

        # Initialize members of the class
        self.name = name 
        self.description = description 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        name = dictionary.get("name") if dictionary.get("name") else None
        description = dictionary.get("description") if dictionary.get("description") else None
        # Return an object of this model
        return cls(name,
                   description)
