"""apimaticapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class ExportFormats(object):
    """Implementation of the 'ExportFormats' enum.

    The structure contains API specification formats that Transformer can convert to.

    Attributes:
        APIMATIC: The enum member of type str.
        WADL2009: The enum member of type str.
        WSDL: The enum member of type str.
        SWAGGER10: The enum member of type str.
        SWAGGER20: The enum member of type str.
        SWAGGERYAML: The enum member of type str.
        OAS3: OpenAPI v3.0 (JSON)
        OPENAPI3YAML: The enum member of type str.
        APIBLUEPRINT: The enum member of type str.
        RAML: The enum member of type str.
        RAML10: The enum member of type str.
        POSTMAN10: The enum member of type str.
        POSTMAN20: The enum member of type str.
        GRAPHQLSCHEMA: The enum member of type str.

    """

    APIMATIC = "APIMATIC"

    WADL2009 = "WADL2009"

    WSDL = "WSDL"

    SWAGGER10 = "Swagger10"

    SWAGGER20 = "Swagger20"

    SWAGGERYAML = "SwaggerYaml"

    OAS3 = "OpenApi3Json"

    OPENAPI3YAML = "OpenApi3Yaml"

    APIBLUEPRINT = "APIBluePrint"

    RAML = "RAML"

    RAML10 = "RAML10"

    POSTMAN10 = "Postman10"

    POSTMAN20 = "Postman20"

    GRAPHQLSCHEMA = "GraphQlSchema"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
