# -*- coding: utf-8 -*-

"""
apimaticapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ExportFormats(object):

    """Implementation of the 'ExportFormats' enum.

    The structure contains API specification formats that Transformer can
    convert to.

    Attributes:
        APIMATIC: TODO: type description here.
        WADL2009: TODO: type description here.
        WSDL: TODO: type description here.
        SWAGGER10: TODO: type description here.
        SWAGGER20: TODO: type description here.
        SWAGGERYAML: TODO: type description here.
        OAS3: OpenAPI v3.0 (JSON)
        OPENAPI3YAML: TODO: type description here.
        APIBLUEPRINT: TODO: type description here.
        RAML: TODO: type description here.
        RAML10: TODO: type description here.
        POSTMAN10: TODO: type description here.
        POSTMAN20: TODO: type description here.
        GRAPHQLSCHEMA: TODO: type description here.

    """
    APIMATIC = 'APIMATIC'

    WADL2009 = 'WADL2009'

    WSDL = 'WSDL'

    SWAGGER10 = 'Swagger10'

    SWAGGER20 = 'Swagger20'

    SWAGGERYAML = 'SwaggerYaml'

    OAS3 = 'OpenApi3Json'

    OPENAPI3YAML = 'OpenApi3Yaml'

    APIBLUEPRINT = 'APIBluePrint'

    RAML = 'RAML'

    RAML10 = 'RAML10'

    POSTMAN10 = 'Postman10'

    POSTMAN20 = 'Postman20'

    GRAPHQLSCHEMA = 'GraphQlSchema'

