# -*- coding: utf-8 -*-

"""
apimaticapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class GenerateSdkViaUrlRequest(object):

    """Implementation of the 'GenerateSdkViaUrlRequest' model.

    TODO: type model description here.

    Attributes:
        url (str): The URL for the API specification file.<br><br>**Note:**
            This URL should be publicly accessible.
        template (Platforms): The structure contains platforms that APIMatic
            CodeGen can generate SDKs and Docs in.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "url": 'url',
        "template": 'template'
    }

    def __init__(self,
                 url=None,
                 template='CS_NET_STANDARD_LIB'):
        """Constructor for the GenerateSdkViaUrlRequest class"""

        # Initialize members of the class
        self.url = url 
        self.template = template 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        url = dictionary.get("url") if dictionary.get("url") else None
        template = dictionary.get("template") if dictionary.get("template") else 'CS_NET_STANDARD_LIB'
        # Return an object of this model
        return cls(url,
                   template)
