"""apimaticapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimaticapi.api_helper import APIHelper


class GenerateSdkViaUrlRequest(object):
    """Implementation of the 'GenerateSdkViaUrlRequest' model.

    Attributes:
        url (str): The URL for the API specification file.<br><br>**Note:** This URL
            should be publicly accessible.
        template (Platforms): The structure contains platforms that APIMatic CodeGen
            can generate SDKs and Docs in.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "url": "url",
        "template": "template",
    }

    def __init__(
        self,
        url=None,
        template="CS_NET_STANDARD_LIB",
        additional_properties=None):
        """Initialize a GenerateSdkViaUrlRequest instance."""
        # Initialize members of the class
        self.url = url
        self.template = template

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else None
        template =\
            dictionary.get("template")\
            if dictionary.get("template")\
                else "CS_NET_STANDARD_LIB"

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(url,
                   template,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _url=self.url
        _template=self.template
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"url={_url!r}, "
            f"template={_template!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _url=self.url
        _template=self.template
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"url={_url!s}, "
            f"template={_template!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
