# -*- coding: utf-8 -*-

"""
apimaticapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class InplaceImportApiViaUrlRequest(object):

    """Implementation of the 'InplaceImportApiViaUrlRequest' model.

    Contains a url field to allow Apis to be imported via url

    Attributes:
        url (str): The URL for the API specification file.<br><br>**Note:**
            This URL should be publicly accessible.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "url": 'url'
    }

    def __init__(self,
                 url=None):
        """Constructor for the InplaceImportApiViaUrlRequest class"""

        # Initialize members of the class
        self.url = url 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        url = dictionary.get("url") if dictionary.get("url") else None
        # Return an object of this model
        return cls(url)
