"""apimaticapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimaticapi.api_helper import APIHelper


class LineInfo(object):
    """Implementation of the 'LineInfo' model.

    Attributes:
        start_line_number (int): The model property of type int.
        start_line_position (int): The model property of type int.
        end_line_number (int): The model property of type int.
        end_line_position (int): The model property of type int.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "start_line_number": "startLineNumber",
        "start_line_position": "startLinePosition",
        "end_line_number": "endLineNumber",
        "end_line_position": "endLinePosition",
    }

    def __init__(
        self,
        start_line_number=None,
        start_line_position=None,
        end_line_number=None,
        end_line_position=None,
        additional_properties=None):
        """Initialize a LineInfo instance."""
        # Initialize members of the class
        self.start_line_number = start_line_number
        self.start_line_position = start_line_position
        self.end_line_number = end_line_number
        self.end_line_position = end_line_position

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        start_line_number =\
            dictionary.get("startLineNumber")\
            if dictionary.get("startLineNumber")\
                else None
        start_line_position =\
            dictionary.get("startLinePosition")\
            if dictionary.get("startLinePosition")\
                else None
        end_line_number =\
            dictionary.get("endLineNumber")\
            if dictionary.get("endLineNumber")\
                else None
        end_line_position =\
            dictionary.get("endLinePosition")\
            if dictionary.get("endLinePosition")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(start_line_number,
                   start_line_position,
                   end_line_number,
                   end_line_position,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _start_line_number=self.start_line_number
        _start_line_position=self.start_line_position
        _end_line_number=self.end_line_number
        _end_line_position=self.end_line_position
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"start_line_number={_start_line_number!r}, "
            f"start_line_position={_start_line_position!r}, "
            f"end_line_number={_end_line_number!r}, "
            f"end_line_position={_end_line_position!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _start_line_number=self.start_line_number
        _start_line_position=self.start_line_position
        _end_line_number=self.end_line_number
        _end_line_position=self.end_line_position
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"start_line_number={_start_line_number!s}, "
            f"start_line_position={_start_line_position!s}, "
            f"end_line_number={_end_line_number!s}, "
            f"end_line_position={_end_line_position!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
