# -*- coding: utf-8 -*-

"""
apimaticapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ParamterFormatDetails(object):

    """Implementation of the 'ParamterFormatDetails' model.

    TODO: type model description here.

    Attributes:
        param_format (str): Specify Parameter Format

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "param_format": 'ParamFormat'
    }

    def __init__(self,
                 param_format=None):
        """Constructor for the ParamterFormatDetails class"""

        # Initialize members of the class
        self.param_format = param_format 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        param_format = dictionary.get("ParamFormat") if dictionary.get("ParamFormat") else None
        # Return an object of this model
        return cls(param_format)
