"""apimaticapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Platforms(object):
    """Implementation of the 'Platforms' enum.

    The structure contains platforms that APIMatic CodeGen can generate SDKs and Docs
    in.

    Attributes:
        CS_NET_STANDARD_LIB: .NET Standard Library
        JAVA_ECLIPSE_JRE_LIB: JAVA
        PHP_GENERIC_LIB_V2: PHP
        PYTHON_GENERIC_LIB: Python
        RUBY_GENERIC_LIB: Ruby
        TS_GENERIC_LIB: Typescript
        GO_GENERIC_LIB: Go

    """

    CS_NET_STANDARD_LIB = "CS_NET_STANDARD_LIB"

    JAVA_ECLIPSE_JRE_LIB = "JAVA_ECLIPSE_JRE_LIB"

    PHP_GENERIC_LIB_V2 = "PHP_GENERIC_LIB_V2"

    PYTHON_GENERIC_LIB = "PYTHON_GENERIC_LIB"

    RUBY_GENERIC_LIB = "RUBY_GENERIC_LIB"

    TS_GENERIC_LIB = "TS_GENERIC_LIB"

    GO_GENERIC_LIB = "GO_GENERIC_LIB"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
