# -*- coding: utf-8 -*-

"""
apimaticapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Platforms(object):

    """Implementation of the 'Platforms' enum.

    The structure contains platforms that APIMatic CodeGen can generate SDKs
    and Docs in.

    Attributes:
        CS_NET_STANDARD_LIB: .NET Standard Library
        JAVA_ECLIPSE_JRE_LIB: JAVA
        PHP_GENERIC_LIB_V2: PHP
        PYTHON_GENERIC_LIB: Python
        RUBY_GENERIC_LIB: Ruby
        TS_GENERIC_LIB: Typescript
        GO_GENERIC_LIB: Go

    """
    CS_NET_STANDARD_LIB = 'CS_NET_STANDARD_LIB'

    JAVA_ECLIPSE_JRE_LIB = 'JAVA_ECLIPSE_JRE_LIB'

    PHP_GENERIC_LIB_V2 = 'PHP_GENERIC_LIB'

    PYTHON_GENERIC_LIB = 'PYTHON_GENERIC_LIB'

    RUBY_GENERIC_LIB = 'RUBY_GENERIC_LIB'

    TS_GENERIC_LIB = 'TS_GENERIC_LIB'

    GO_GENERIC_LIB = 'GO_GENERIC_LIB'

