"""apimaticapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimaticapi.models.links import Links


class PortalGenerationAsyncResponse(object):
    """Implementation of the 'PortalGenerationAsyncResponse' model.

    Attributes:
        id (uuid|str): The model property of type uuid|str.
        links (Links): The model property of type Links.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "links": "links",
    }

    def __init__(
        self,
        id=None,
        links=None):
        """Initialize a PortalGenerationAsyncResponse instance."""
        # Initialize members of the class
        self.id = id
        self.links = links

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        links =\
            Links.from_dictionary(
                dictionary.get("links"))\
                if dictionary.get("links") else None

        # Return an object of this model
        return cls(id,
                   links)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _links=self.links
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"links={_links!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _links=self.links
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"links={_links!s}, "
            f")"
        )
