"""apimaticapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimaticapi.api_helper import APIHelper


class PortalGenerationStatusResponse(object):
    """Implementation of the 'PortalGenerationStatusResponse' model.

    Attributes:
        status (Status): The model property of type Status.
        errors (Dict[str, Any]): The model property of type Dict[str, Any].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "status": "status",
        "errors": "errors",
    }

    _optionals = [
        "errors",
    ]

    def __init__(
        self,
        status=None,
        errors=APIHelper.SKIP):
        """Initialize a PortalGenerationStatusResponse instance."""
        # Initialize members of the class
        self.status = status
        if errors is not APIHelper.SKIP:
            self.errors = errors

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else None
        errors =\
            dictionary.get("errors")\
            if dictionary.get("errors")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(status,
                   errors)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _status=self.status
        _errors=(
            self.errors
            if hasattr(self, "errors")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"status={_status!r}, "
            f"errors={_errors!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _status=self.status
        _errors=(
            self.errors
            if hasattr(self, "errors")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"status={_status!s}, "
            f"errors={_errors!s}, "
            f")"
        )
