"""apimaticapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimaticapi.api_helper import APIHelper
from apimaticapi.models.api_validation_summary import (
    ApiValidationSummary,
)


class Transformation(object):
    """Implementation of the 'Transformation' model.

    Transformation structure encapsulates all the details of a Transformation.

    Attributes:
        id (str): Unique Transformation Identifier
        transformed_on (str): Transformation Date and Time
        user_id (str): Unique User Identifier
        inputted_file (str): API Specification file to be transformed
        generated_file (str): API Specification file transformed to desired format
        export_format (str): Desired Specification format
        transformation_source (str): Source of Transformation
        transformation_input (str): Via File or URL
        code_gen_version (str): CodeGen Engine Version
        success (bool): Successful Transformation Flag
        import_summary (ApiValidationSummary): The model property of type
            ApiValidationSummary.
        api_validation_summary (ApiValidationSummary): The model property of type
            ApiValidationSummary.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "transformed_on": "transformedOn",
        "user_id": "userId",
        "inputted_file": "inputtedFile",
        "generated_file": "generatedFile",
        "export_format": "exportFormat",
        "transformation_source": "transformationSource",
        "transformation_input": "transformationInput",
        "code_gen_version": "codeGenVersion",
        "success": "success",
        "import_summary": "importSummary",
        "api_validation_summary": "apiValidationSummary",
    }

    def __init__(
        self,
        id=None,
        transformed_on=None,
        user_id=None,
        inputted_file=None,
        generated_file=None,
        export_format=None,
        transformation_source=None,
        transformation_input=None,
        code_gen_version=None,
        success=None,
        import_summary=None,
        api_validation_summary=None,
        additional_properties=None):
        """Initialize a Transformation instance."""
        # Initialize members of the class
        self.id = id
        self.transformed_on = transformed_on
        self.user_id = user_id
        self.inputted_file = inputted_file
        self.generated_file = generated_file
        self.export_format = export_format
        self.transformation_source = transformation_source
        self.transformation_input = transformation_input
        self.code_gen_version = code_gen_version
        self.success = success
        self.import_summary = import_summary
        self.api_validation_summary = api_validation_summary

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        transformed_on =\
            dictionary.get("transformedOn")\
            if dictionary.get("transformedOn")\
                else None
        user_id =\
            dictionary.get("userId")\
            if dictionary.get("userId")\
                else None
        inputted_file =\
            dictionary.get("inputtedFile")\
            if dictionary.get("inputtedFile")\
                else None
        generated_file =\
            dictionary.get("generatedFile")\
            if dictionary.get("generatedFile")\
                else None
        export_format =\
            dictionary.get("exportFormat")\
            if dictionary.get("exportFormat")\
                else None
        transformation_source =\
            dictionary.get("transformationSource")\
            if dictionary.get("transformationSource")\
                else None
        transformation_input =\
            dictionary.get("transformationInput")\
            if dictionary.get("transformationInput")\
                else None
        code_gen_version =\
            dictionary.get("codeGenVersion")\
            if dictionary.get("codeGenVersion")\
                else None
        success =\
            dictionary.get("success")\
            if "success" in dictionary.keys()\
                else None
        import_summary =\
            ApiValidationSummary.from_dictionary(
                dictionary.get("importSummary"))\
                if dictionary.get("importSummary") else None
        api_validation_summary =\
            ApiValidationSummary.from_dictionary(
                dictionary.get("apiValidationSummary"))\
                if dictionary.get("apiValidationSummary") else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   transformed_on,
                   user_id,
                   inputted_file,
                   generated_file,
                   export_format,
                   transformation_source,
                   transformation_input,
                   code_gen_version,
                   success,
                   import_summary,
                   api_validation_summary,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _transformed_on=self.transformed_on
        _user_id=self.user_id
        _inputted_file=self.inputted_file
        _generated_file=self.generated_file
        _export_format=self.export_format
        _transformation_source=self.transformation_source
        _transformation_input=self.transformation_input
        _code_gen_version=self.code_gen_version
        _success=self.success
        _import_summary=self.import_summary
        _api_validation_summary=self.api_validation_summary
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"transformed_on={_transformed_on!r}, "
            f"user_id={_user_id!r}, "
            f"inputted_file={_inputted_file!r}, "
            f"generated_file={_generated_file!r}, "
            f"export_format={_export_format!r}, "
            f"transformation_source={_transformation_source!r}, "
            f"transformation_input={_transformation_input!r}, "
            f"code_gen_version={_code_gen_version!r}, "
            f"success={_success!r}, "
            f"import_summary={_import_summary!r}, "
            f"api_validation_summary={_api_validation_summary!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _transformed_on=self.transformed_on
        _user_id=self.user_id
        _inputted_file=self.inputted_file
        _generated_file=self.generated_file
        _export_format=self.export_format
        _transformation_source=self.transformation_source
        _transformation_input=self.transformation_input
        _code_gen_version=self.code_gen_version
        _success=self.success
        _import_summary=self.import_summary
        _api_validation_summary=self.api_validation_summary
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"transformed_on={_transformed_on!s}, "
            f"user_id={_user_id!s}, "
            f"inputted_file={_inputted_file!s}, "
            f"generated_file={_generated_file!s}, "
            f"export_format={_export_format!s}, "
            f"transformation_source={_transformation_source!s}, "
            f"transformation_input={_transformation_input!s}, "
            f"code_gen_version={_code_gen_version!s}, "
            f"success={_success!s}, "
            f"import_summary={_import_summary!s}, "
            f"api_validation_summary={_api_validation_summary!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
