"""apimaticapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimaticapi.api_helper import APIHelper


class TransformViaUrlRequest(object):
    """Implementation of the 'TransformViaUrlRequest' model.

    This structure puts together the URL of the file to be transformed, along with
    the desired export format.

    Attributes:
        url (str): The URL for the API specification file.<br><br>**Note:** This URL
            should be publicly accessible.
        export_format (ExportFormats): The structure contains API specification
            formats that Transformer can convert to.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "url": "url",
        "export_format": "export_format",
    }

    def __init__(
        self,
        url=None,
        export_format=None,
        additional_properties=None):
        """Initialize a TransformViaUrlRequest instance."""
        # Initialize members of the class
        self.url = url
        self.export_format = export_format

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else None
        export_format =\
            dictionary.get("export_format")\
            if dictionary.get("export_format")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(url,
                   export_format,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _url=self.url
        _export_format=self.export_format
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"url={_url!r}, "
            f"export_format={_export_format!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _url=self.url
        _export_format=self.export_format
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"url={_url!s}, "
            f"export_format={_export_format!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
