"""apimaticapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimaticapi.api_helper import APIHelper


class UserCodeGeneration(object):
    """Implementation of the 'UserCodeGeneration' model.

    The Code Generation structure encapsulates all the  the details of an SDK
    generation performed by a user.

    Attributes:
        id (str): Unique Code Generation Identifier
        template (Platforms): The structure contains platforms that APIMatic CodeGen
            can generate SDKs and Docs in.
        generated_file (str): The generated SDK
        generated_on (datetime): Generation Date and Time
        hash_code (str): The md5 hash of the API Description
        code_generation_source (str): Generation Source
        code_gen_version (str): Generation Version
        success (bool): Generation Status
        user_id (str): Unique User Identifier
        input_file (str): API Specification file in a supported format
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "template": "template",
        "generated_file": "generatedFile",
        "generated_on": "generatedOn",
        "hash_code": "hashCode",
        "code_generation_source": "codeGenerationSource",
        "code_gen_version": "codeGenVersion",
        "success": "success",
        "user_id": "userId",
        "input_file": "inputFile",
    }

    def __init__(
        self,
        id=None,
        template="CS_NET_STANDARD_LIB",
        generated_file=None,
        generated_on=None,
        hash_code=None,
        code_generation_source=None,
        code_gen_version=None,
        success=None,
        user_id=None,
        input_file=None,
        additional_properties=None):
        """Initialize a UserCodeGeneration instance."""
        # Initialize members of the class
        self.id = id
        self.template = template
        self.generated_file = generated_file
        self.generated_on =\
             APIHelper.apply_datetime_converter(
            generated_on, APIHelper.RFC3339DateTime)\
             if generated_on else None
        self.hash_code = hash_code
        self.code_generation_source = code_generation_source
        self.code_gen_version = code_gen_version
        self.success = success
        self.user_id = user_id
        self.input_file = input_file

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        template =\
            dictionary.get("template")\
            if dictionary.get("template")\
                else "CS_NET_STANDARD_LIB"
        generated_file =\
            dictionary.get("generatedFile")\
            if dictionary.get("generatedFile")\
                else None
        generated_on = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("generatedOn")).datetime\
            if dictionary.get("generatedOn") else None
        hash_code =\
            dictionary.get("hashCode")\
            if dictionary.get("hashCode")\
                else None
        code_generation_source =\
            dictionary.get("codeGenerationSource")\
            if dictionary.get("codeGenerationSource")\
                else None
        code_gen_version =\
            dictionary.get("codeGenVersion")\
            if dictionary.get("codeGenVersion")\
                else None
        success =\
            dictionary.get("success")\
            if "success" in dictionary.keys()\
                else None
        user_id =\
            dictionary.get("userId")\
            if dictionary.get("userId")\
                else None
        input_file =\
            dictionary.get("inputFile")\
            if dictionary.get("inputFile")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   template,
                   generated_file,
                   generated_on,
                   hash_code,
                   code_generation_source,
                   code_gen_version,
                   success,
                   user_id,
                   input_file,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _template=self.template
        _generated_file=self.generated_file
        _generated_on=self.generated_on
        _hash_code=self.hash_code
        _code_generation_source=self.code_generation_source
        _code_gen_version=self.code_gen_version
        _success=self.success
        _user_id=self.user_id
        _input_file=self.input_file
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"template={_template!r}, "
            f"generated_file={_generated_file!r}, "
            f"generated_on={_generated_on!r}, "
            f"hash_code={_hash_code!r}, "
            f"code_generation_source={_code_generation_source!r}, "
            f"code_gen_version={_code_gen_version!r}, "
            f"success={_success!r}, "
            f"user_id={_user_id!r}, "
            f"input_file={_input_file!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _template=self.template
        _generated_file=self.generated_file
        _generated_on=self.generated_on
        _hash_code=self.hash_code
        _code_generation_source=self.code_generation_source
        _code_gen_version=self.code_gen_version
        _success=self.success
        _user_id=self.user_id
        _input_file=self.input_file
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"template={_template!s}, "
            f"generated_file={_generated_file!s}, "
            f"generated_on={_generated_on!s}, "
            f"hash_code={_hash_code!s}, "
            f"code_generation_source={_code_generation_source!s}, "
            f"code_gen_version={_code_gen_version!s}, "
            f"success={_success!s}, "
            f"user_id={_user_id!s}, "
            f"input_file={_input_file!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
