"""apimaticapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimaticapi.api_helper import APIHelper
from apimaticapi.models.line_info import LineInfo


class ValidationEntry(object):
    """Implementation of the 'ValidationEntry' model.

    Attributes:
        message (str): The model property of type str.
        line_info (LineInfo): The model property of type LineInfo.
        json_reference_path (str): The model property of type str.
        file_reference (str): The model property of type str.
        metadata (Dict[str, str]): The model property of type Dict[str, str].
        rule_documentation_reference (str): The model property of type str.
        additional_references (List[str]): The model property of type List[str].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "message": "message",
        "line_info": "lineInfo",
        "json_reference_path": "jsonReferencePath",
        "file_reference": "fileReference",
        "metadata": "metadata",
        "rule_documentation_reference": "ruleDocumentationReference",
        "additional_references": "additionalReferences",
    }

    _optionals = [
        "line_info",
        "json_reference_path",
        "file_reference",
        "metadata",
        "rule_documentation_reference",
        "additional_references",
    ]

    def __init__(
        self,
        message=None,
        line_info=APIHelper.SKIP,
        json_reference_path=APIHelper.SKIP,
        file_reference=APIHelper.SKIP,
        metadata=APIHelper.SKIP,
        rule_documentation_reference=APIHelper.SKIP,
        additional_references=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ValidationEntry instance."""
        # Initialize members of the class
        self.message = message
        if line_info is not APIHelper.SKIP:
            self.line_info = line_info
        if json_reference_path is not APIHelper.SKIP:
            self.json_reference_path = json_reference_path
        if file_reference is not APIHelper.SKIP:
            self.file_reference = file_reference
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata
        if rule_documentation_reference is not APIHelper.SKIP:
            self.rule_documentation_reference = rule_documentation_reference
        if additional_references is not APIHelper.SKIP:
            self.additional_references = additional_references

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        message =\
            dictionary.get("message")\
            if dictionary.get("message")\
                else None
        line_info =\
            LineInfo.from_dictionary(
                dictionary.get("lineInfo"))\
                if "lineInfo" in dictionary.keys()\
                else APIHelper.SKIP
        json_reference_path =\
            dictionary.get("jsonReferencePath")\
            if dictionary.get("jsonReferencePath")\
                else APIHelper.SKIP
        file_reference =\
            dictionary.get("fileReference")\
            if dictionary.get("fileReference")\
                else APIHelper.SKIP
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else APIHelper.SKIP
        rule_documentation_reference =\
            dictionary.get("ruleDocumentationReference")\
            if dictionary.get("ruleDocumentationReference")\
                else APIHelper.SKIP
        additional_references =\
            dictionary.get("additionalReferences")\
            if dictionary.get("additionalReferences")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(message,
                   line_info,
                   json_reference_path,
                   file_reference,
                   metadata,
                   rule_documentation_reference,
                   additional_references,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _message=self.message
        _line_info=(
            self.line_info
            if hasattr(self, "line_info")
            else None
        )
        _json_reference_path=(
            self.json_reference_path
            if hasattr(self, "json_reference_path")
            else None
        )
        _file_reference=(
            self.file_reference
            if hasattr(self, "file_reference")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _rule_documentation_reference=(
            self.rule_documentation_reference
            if hasattr(self, "rule_documentation_reference")
            else None
        )
        _additional_references=(
            self.additional_references
            if hasattr(self, "additional_references")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"message={_message!r}, "
            f"line_info={_line_info!r}, "
            f"json_reference_path={_json_reference_path!r}, "
            f"file_reference={_file_reference!r}, "
            f"metadata={_metadata!r}, "
            f"rule_documentation_reference={_rule_documentation_reference!r}, "
            f"additional_references={_additional_references!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _message=self.message
        _line_info=(
            self.line_info
            if hasattr(self, "line_info")
            else None
        )
        _json_reference_path=(
            self.json_reference_path
            if hasattr(self, "json_reference_path")
            else None
        )
        _file_reference=(
            self.file_reference
            if hasattr(self, "file_reference")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _rule_documentation_reference=(
            self.rule_documentation_reference
            if hasattr(self, "rule_documentation_reference")
            else None
        )
        _additional_references=(
            self.additional_references
            if hasattr(self, "additional_references")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"message={_message!s}, "
            f"line_info={_line_info!s}, "
            f"json_reference_path={_json_reference_path!s}, "
            f"file_reference={_file_reference!s}, "
            f"metadata={_metadata!s}, "
            f"rule_documentation_reference={_rule_documentation_reference!s}, "
            f"additional_references={_additional_references!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
