"""apimaticapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimaticapi.api_helper import APIHelper
from apimaticapi.models.validation_entry import (
    ValidationEntry,
)


class ValidationSummary(object):
    """Implementation of the 'ValidationSummary' model.

    Attributes:
        is_success (bool): The model property of type bool.
        blocking (List[ValidationEntry]): The model property of type
            List[ValidationEntry].
        errors (List[ValidationEntry]): The model property of type
            List[ValidationEntry].
        warnings (List[ValidationEntry]): The model property of type
            List[ValidationEntry].
        information (List[ValidationEntry]): The model property of type
            List[ValidationEntry].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "is_success": "isSuccess",
        "blocking": "blocking",
        "errors": "errors",
        "warnings": "warnings",
        "information": "information",
    }

    def __init__(
        self,
        is_success=None,
        blocking=None,
        errors=None,
        warnings=None,
        information=None,
        additional_properties=None):
        """Initialize a ValidationSummary instance."""
        # Initialize members of the class
        self.is_success = is_success
        self.blocking = blocking
        self.errors = errors
        self.warnings = warnings
        self.information = information

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        is_success =\
            dictionary.get("isSuccess")\
            if "isSuccess" in dictionary.keys()\
                else None
        blocking = None
        if dictionary.get("blocking") is not None:
            blocking = [
                ValidationEntry.from_dictionary(x)
                    for x in dictionary.get("blocking")
            ]
        errors = None
        if dictionary.get("errors") is not None:
            errors = [
                ValidationEntry.from_dictionary(x)
                    for x in dictionary.get("errors")
            ]
        warnings = None
        if dictionary.get("warnings") is not None:
            warnings = [
                ValidationEntry.from_dictionary(x)
                    for x in dictionary.get("warnings")
            ]
        information = None
        if dictionary.get("information") is not None:
            information = [
                ValidationEntry.from_dictionary(x)
                    for x in dictionary.get("information")
            ]

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(is_success,
                   blocking,
                   errors,
                   warnings,
                   information,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _is_success=self.is_success
        _blocking=self.blocking
        _errors=self.errors
        _warnings=self.warnings
        _information=self.information
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"is_success={_is_success!r}, "
            f"blocking={_blocking!r}, "
            f"errors={_errors!r}, "
            f"warnings={_warnings!r}, "
            f"information={_information!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _is_success=self.is_success
        _blocking=self.blocking
        _errors=self.errors
        _warnings=self.warnings
        _information=self.information
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"is_success={_is_success!s}, "
            f"blocking={_blocking!s}, "
            f"errors={_errors!s}, "
            f"warnings={_warnings!s}, "
            f"information={_information!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
